name: Emcc Compiler Website Builder

run-name: ${{ github.actor }} is building website 🚀

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup EMSDK
        uses: mymindstorm/setup-emsdk@v14

      - name: Verify EMSDK
        run: emcc -v

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Webasm
        run: make webasm
      
      - name: build tutorial
        run: python3 .github/generate_examply.py
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
