name: Test Runner

run-name: ${{ github.actor }} is running tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Download Zig 0.15.1
        run: |
          wget https://ziglang.org/download/0.15.1/zig-x86_64-linux-0.15.1.tar.xz
          tar -xf zig-x86_64-linux-0.15.1.tar.xz
          echo "$(pwd)/zig-x86_64-linux-0.15.1" >> $GITHUB_PATH
          echo "$(pwd)/zig-x86_64-linux-0.15.1.tar.xz"
          cat $GITHUB_PATH

      - name: Verify Zig
        run: zig version

      
      - name: Running tests
        run: zig build test
